/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Jogador;
import model.JogadorDAO;
import model.Jogar;

/**
 *
 * @author aesshedai
 */
public class JogoPrincipal extends javax.swing.JFrame {

    Jogador jogador;
    Jogador computador = new Jogador();

    public JogoPrincipal() {
        initComponents();

    }

    public JogoPrincipal(Jogador jogador) {
        this.jogador = jogador;
        initComponents();

        lJogadorPontuacao2.setText(jogador.getNomeJogador());
        this.setLocale(null);
        this.setLocationRelativeTo(null);
    }
    
    public void atualizaResultados(){      
        txtGanhouComptador.setText("" + computador.getGanhouPontuacao());
        txtGanhouJogador.setText("" + jogador.getGanhouPontuacao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bSalvar = new javax.swing.JButton();
        txtEscolhaComputador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lJogador = new javax.swing.JLabel();
        txtEscolhaJogador = new javax.swing.JTextField();
        txtResultado = new javax.swing.JTextField();
        jPanelPapel = new javax.swing.JPanel();
        jPanelTesoura = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lJogadorPontuacao2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtGanhouComptador = new javax.swing.JTextField();
        txtGanhouJogador = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanelPedra = new javax.swing.JPanel();
        lTesoura = new javax.swing.JLabel();
        lPapel = new javax.swing.JLabel();
        labelPedra = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bSalvar.setBackground(new java.awt.Color(153, 153, 0));
        bSalvar.setFont(new java.awt.Font("Courier 10 Pitch", 1, 24)); // NOI18N
        bSalvar.setForeground(new java.awt.Color(255, 255, 255));
        bSalvar.setText("Salvar e Sair!");
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(bSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 260, 40));

        txtEscolhaComputador.setEditable(false);
        txtEscolhaComputador.setFont(new java.awt.Font("Courier 10 Pitch", 0, 24)); // NOI18N
        txtEscolhaComputador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEscolhaComputadorActionPerformed(evt);
            }
        });
        getContentPane().add(txtEscolhaComputador, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 220, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/computador.png"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        lJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/jogador.png"))); // NOI18N
        lJogador.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(lJogador, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        txtEscolhaJogador.setEditable(false);
        txtEscolhaJogador.setFont(new java.awt.Font("Courier 10 Pitch", 1, 24)); // NOI18N
        txtEscolhaJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEscolhaJogadorActionPerformed(evt);
            }
        });
        getContentPane().add(txtEscolhaJogador, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 220, -1));

        txtResultado.setEditable(false);
        txtResultado.setBackground(new java.awt.Color(255, 255, 255));
        txtResultado.setFont(new java.awt.Font("Courier 10 Pitch", 2, 24)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(255, 0, 0));
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultado.setEnabled(false);
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });
        getContentPane().add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 299, -1));

        jPanelPapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelPapelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelPapelMouseEntered(evt);
            }
        });
        jPanelPapel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanelPapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 238, -1, -1));

        jPanelTesoura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelTesouraMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelTesouraMouseEntered(evt);
            }
        });
        jPanelTesoura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanelTesoura, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 256, -1, -1));

        jLabel1.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, -1, -1));

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lJogadorPontuacao2.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        lJogadorPontuacao2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lJogadorPontuacao2.setText("jLabel8");
        jPanel1.add(lJogadorPontuacao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, -1));

        jLabel9.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Computador");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 97, -1));

        jLabel12.setFont(new java.awt.Font("Courier 10 Pitch", 1, 18)); // NOI18N
        jLabel12.setText("X");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 70, -1, -1));

        txtGanhouComptador.setEditable(false);
        jPanel1.add(txtGanhouComptador, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 97, -1));

        txtGanhouJogador.setEditable(false);
        jPanel1.add(txtGanhouJogador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 102, -1));

        jLabel7.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PONTUAÇÃO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 116, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 310, 140));

        jPanelPedra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelPedraMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelPedraMouseEntered(evt);
            }
        });
        jPanelPedra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanelPedra, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 238, -1, 219));

        lTesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/scissors.png"))); // NOI18N
        lTesoura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lTesouraMouseClicked(evt);
            }
        });
        getContentPane().add(lTesoura, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, -1, -1));

        lPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/paper.png"))); // NOI18N
        lPapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPapelMouseClicked(evt);
            }
        });
        getContentPane().add(lPapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        labelPedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/rock.png"))); // NOI18N
        labelPedra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPedraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelPedraMouseEntered(evt);
            }
        });
        getContentPane().add(labelPedra, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        jLabel3.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("O computador escolheu:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 240, -1));

        jLabel4.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Você escolheu:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 250, -1));

        jLabel5.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Resultado da Partida!");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 230, -1));

        jLabel6.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Escolha uma das opções:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 250, -1));

        jLabel8.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Pedra");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 110, -1));

        jLabel10.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Papel");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 110, -1));

        jLabel11.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Tesoura");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
        JogadorDAO salvar = new JogadorDAO();
        try {
            salvar.inserir(this.jogador);
        } catch (SQLException ex) {
            Logger.getLogger(JogoPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_bSalvarActionPerformed

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed

    }//GEN-LAST:event_txtResultadoActionPerformed

    private void txtEscolhaComputadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEscolhaComputadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEscolhaComputadorActionPerformed

    private void txtEscolhaJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEscolhaJogadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEscolhaJogadorActionPerformed

    private void labelPedraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPedraMouseClicked
        Jogar j = new Jogar(this.jogador, this.computador);
        String a = this.jogador.escolhe(0);
        String b = this.computador.escolhaAleatoria();
        txtResultado.setText(j.jogar(a, b));
        txtEscolhaJogador.setText(a.toUpperCase());
        txtEscolhaComputador.setText(b.toUpperCase());
        
        System.out.println("Funcionou");
        
        this.atualizaResultados();
    }//GEN-LAST:event_labelPedraMouseClicked

    private void lPapelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPapelMouseClicked
        Jogar j = new Jogar(this.jogador, this.computador);
        String a = this.jogador.escolhe(1);
        String b = this.computador.escolhaAleatoria();
        txtResultado.setText(j.jogar(a, b));
        txtEscolhaJogador.setText(a.toUpperCase());
        txtEscolhaComputador.setText(b.toUpperCase());
        System.out.println("Funcionou");
        this.atualizaResultados();
    }//GEN-LAST:event_lPapelMouseClicked

    private void labelPedraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPedraMouseEntered
            
    }//GEN-LAST:event_labelPedraMouseEntered

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
        jPanel1.setBackground(new Color(45, 118, 232));
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        // TODO add your handling code here:
        jPanel1.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_jPanel1MouseExited

    private void jPanelPedraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPedraMouseEntered
        jPanelPedra.setBackground(new Color(45, 118, 232));
    }//GEN-LAST:event_jPanelPedraMouseEntered

    private void jPanelPedraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPedraMouseExited
        jPanelPedra.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_jPanelPedraMouseExited

    private void jPanelTesouraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTesouraMouseEntered
        jPanelTesoura.setBackground(new Color(45, 118, 232));
    }//GEN-LAST:event_jPanelTesouraMouseEntered

    private void jPanelTesouraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTesouraMouseExited
        jPanelTesoura.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_jPanelTesouraMouseExited

    private void jPanelPapelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPapelMouseEntered
        jPanelPapel.setBackground(new Color(45, 118, 232));
    }//GEN-LAST:event_jPanelPapelMouseEntered

    private void jPanelPapelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPapelMouseExited
        jPanelPapel.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_jPanelPapelMouseExited

    private void lTesouraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lTesouraMouseClicked
        Jogar j = new Jogar(this.jogador, this.computador);
        String a = this.jogador.escolhe(2);
        String b = this.computador.escolhaAleatoria();
        txtResultado.setText(j.jogar(a, b));
        txtEscolhaJogador.setText(a.toUpperCase());
        txtEscolhaComputador.setText(b.toUpperCase());
        System.out.println("Funcionou");
        this.atualizaResultados();
    }//GEN-LAST:event_lTesouraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new JogoPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelPapel;
    private javax.swing.JPanel jPanelPedra;
    private javax.swing.JPanel jPanelTesoura;
    private javax.swing.JLabel lJogador;
    private javax.swing.JLabel lJogadorPontuacao2;
    private javax.swing.JLabel lPapel;
    private javax.swing.JLabel lTesoura;
    private javax.swing.JLabel labelPedra;
    private javax.swing.JTextField txtEscolhaComputador;
    private javax.swing.JTextField txtEscolhaJogador;
    private javax.swing.JTextField txtGanhouComptador;
    private javax.swing.JTextField txtGanhouJogador;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
